[buildPlans.AkvesoiCode]
family = "Akvesoi Code"
desc = "Default"
buildCharMap = true
snapshotFamily = "Akvesoi"
snapshotFeature = {"NWID" = 0}
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = false

[buildPlans.AkvesoiCode.variants.design]
capital-d = "more-rounded-serifless"
capital-j = "serifless"
capital-w = "straight-flat-top-serifless"
a = "double-storey-serifless"
g = "double-storey"
i = "tailed-serifed"
j = "serifed"
k = "straight-serifless"
l = "tailed-serifed"
t = "bent-hook"
one = "base"
five = "oblique-arched-serifless"
six = "straight-bar"
eight = "crossing-asymmetric"
punctuation-dot = "round"
brace = "straight"
guillemet = "straight"
number-sign = "upright"
ampersand = "upper-open"
at = "compact"
percent = "rings-continuous-slash"
micro-sign = "tailed-serifless"
lig-equal-chain = "with-notch"
lig-plus-chain = "without-notch"

[buildPlans.AkvesoiCode.ligations]
inherits = "dlig"

[buildPlans.AkvesoiCode.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.AkvesoiCode.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.AkvesoiTerm]
family = "Akvesoi Term"
snapshotFamily = "Akvesoi"
snapshotFeature = {"NWID" = 1}
spacing = "term"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

[buildPlans.AkvesoiTerm.variants.design]
capital-d = "more-rounded-serifless"
capital-j = "serifless"
capital-w = "straight-flat-top-serifless"
a = "double-storey-serifless"
g = "double-storey"
i = "tailed-serifed"
j = "serifed"
k = "straight-serifless"
l = "tailed-serifed"
t = "bent-hook"
one = "base"
five = "oblique-arched-serifless"
six = "straight-bar"
eight = "crossing-asymmetric"
punctuation-dot = "round"
brace = "straight"
guillemet = "straight"
number-sign = "upright"
ampersand = "upper-open"
at = "compact"
percent = "rings-continuous-slash"
micro-sign = "tailed-serifless"
lig-equal-chain = "with-notch"
lig-plus-chain = "without-notch"

[buildPlans.AkvesoiTerm.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.AkvesoiTerm.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.AkvesoiMono]
family = "Akvesoi Mono"
snapshotFamily = "Akvesoi"
snapshotFeature = {"NWID" = 1}
spacing = "fixed"
serifs = "sans"
noCvSs = false
exportGlyphNames = true
noLigation = true

[buildPlans.AkvesoiMono.variants.design]
capital-d = "more-rounded-serifless"
capital-j = "serifless"
capital-w = "straight-flat-top-serifless"
a = "double-storey-serifless"
g = "double-storey"
i = "tailed-serifed"
j = "serifed"
k = "straight-serifless"
l = "tailed-serifed"
t = "bent-hook"
one = "base"
five = "oblique-arched-serifless"
six = "straight-bar"
eight = "crossing-asymmetric"
punctuation-dot = "round"
brace = "straight"
guillemet = "straight"
number-sign = "upright"
ampersand = "upper-open"
at = "compact"
percent = "rings-continuous-slash"
micro-sign = "tailed-serifless"

[buildPlans.AkvesoiMono.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.AkvesoiMono.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.AkvesoiType]
family = "Akvesoi Type"
desc = "Slab-serif"
spacing = "quasi-proportional-extension-only"
serifs = "slab"
snapshotFamily = 'Akvesoi'
snapshotFeature = {"NWID" = 0}
noCvSs = false
exportGlyphNames = false

[buildPlans.AkvesoiType.variants.design]
capital-d = "more-rounded-bilateral-serifed"
capital-j = "serifed-both-sides"
capital-w = "straight-flat-top-serifed"
a = "double-storey-hook-inward-serifed-tailed"
g = "single-storey-serifed"
i = "tailed-serifed"
j = "serifed"
l = "tailed-serifed"
one = "base"
five = "oblique-arched-serifed"
six = "straight-bar"
eight = "crossing-asymmetric"
punctuation-dot = "square"
brace = "straight"
guillemet = "straight"
number-sign = "upright"
ampersand = "upper-open"
at = "compact"
percent = "rings-continuous-slash"
lig-equal-chain = "with-notch"
lig-plus-chain = "without-notch"

[buildPlans.AkvesoiType.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.AkvesoiType.widths.Normal]
shape = 600
menu = 5
css = "normal"

[collectPlans.Akvesoi]
release = true
from = ["AkvesoiCode", "AkvesoiTerm", "AkvesoiMono", "AkvesoiType"]
