name: Build fonts

on: 
  push: 
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      iosevkaVersion: ${{ steps.iosevka-version.outputs.version }}
      selfVersion: ${{ steps.self-version.outputs.version }}
    steps: 
      - name: Get Iosevka release version
        id: iosevka-version
        run: |
          curl -sL https://api.github.com/repos/be5invis/Iosevka/releases/latest | \
          jq -r ".tag_name" | \
          sed 's/^v//' | \
          xargs -I {} echo "version={}" >> $GITHUB_OUTPUT
      - name: Get Self release version
        env:
          REPO: ${{ github.action_repository }}
        id: self-version
        run: |
          curl -sL https://api.github.com/repos/$REPO/releases/latest | \
          jq -r ".tag_name" | \
          sed 's/^v//' | \
          xargs -I {} echo "version={}" >> $GITHUB_OUTPUT
  build:
    needs: check
    if: ${{ needs.check.outputs.iosevkaVersion != needs.check.outputs.selfVersion }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '>=18.0.0'
      - name: Get system packages
        run: sudo apt-get install ttfautohint libttfautohint-dev
      - name: Fetch Iosevka release
        env:
          VERSION: ${{ needs.check.outputs.iosevkaVersion }}
        run: |
          curl -L "https://github.com/be5invis/Iosevka/archive/refs/tags/v$VERSION.tar.gz" | \
          tar xz
          mv Iosevka-* src
      - name: Cache Built Fonts
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ./src/dist
            ./src/release-archives
          key: ${{ runner.os }}-build-${{ needs.check.outputs.iosevkaVersion }}
      - name: Build Custom font
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        continue-on-error: true
        run: |
          cp private-build-plans.toml src/private-build-plans.toml
          cd src
          npm install
          sed -i '/release = true/d' build-plans.toml
          npm run build -- release:archives
      # - name: Create tag
      #   uses: rickstaa/action-create-tag@v1
      #   with:
      #     tag: ${{ format('v{0}', needs.check.outputs.iosevkaVersion) }}
      - name: Create Release
        env:
          VERSION: ${{ needs.check.outputs.iosevkaVersion }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ format('refs/tags/v{0}', needs.check.outputs.iosevkaVersion) }}
          name: ${{ format('v{0}', needs.check.outputs.iosevkaVersion) }}
          body: |
            <table>
            <tr><td colspan="3"><b>&#x1F4E6; Akvesoi</b></td><td><b><a href="https://github.com/g-hanwen/Akvesoi/releases/download/v${{ needs.check.outputs.iosevkaVersion }}/SuperTTC-Akvesoi-${{ needs.check.outputs.iosevkaVersion }}.zip">Super TTC</b></td><td><b><a href="https://github.com/g-hanwen/Akvesoi/releases/download/v${{ needs.check.outputs.iosevkaVersion }}/PkgTTC-Akvesoi-${{ needs.check.outputs.iosevkaVersion }}.zip">TTC</b></td><td colspan="2">&nbsp;</td></tr>
            <tr><td><b>&nbsp;&nbsp;└ Sub-packages</b></td><td><b>Spacing</b></td><td><b>Ligatures</b></td><td colspan="4"><b>Downloads</b></td></tr>
            <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;├&nbsp;<b>Akvesoi</b></td><td>Default</td><td><b>Yes</b></td><td><b><a href="https://github.com/g-hanwen/Akvesoi/releases/download/v${{ needs.check.outputs.iosevkaVersion }}/SuperTTC-SGr-Akvesoi-${{ needs.check.outputs.iosevkaVersion }}.zip">Super TTC</a></b></td><td><b><a href="https://github.com/g-hanwen/Akvesoi/releases/download/v${{ needs.check.outputs.iosevkaVersion }}/PkgTTC-SGr-Akvesoi-${{ needs.check.outputs.iosevkaVersion }}.zip">TTC</a></b></td><td><b><a href="https://github.com/g-hanwen/Akvesoi/releases/download/v${{ needs.check.outputs.iosevkaVersion }}/PkgTTF-Akvesoi-${{ needs.check.outputs.iosevkaVersion }}.zip">TTF</a></b>&nbsp;(<b><a href="https://github.com/g-hanwen/Akvesoi/releases/download/v${{ needs.check.outputs.iosevkaVersion }}/PkgTTF-Unhinted-Akvesoi-${{ needs.check.outputs.iosevkaVersion }}.zip">Unhinted</a></b>)</td><td><b><a href="https://github.com/g-hanwen/Akvesoi/releases/download/v${{ needs.check.outputs.iosevkaVersion }}/PkgWebFont-Akvesoi-${{ needs.check.outputs.iosevkaVersion }}.zip">WebFont</a></b>&nbsp;(<b><a href="https://github.com/g-hanwen/Akvesoi/releases/download/v${{ needs.check.outputs.iosevkaVersion }}/PkgWebFont-Unhinted-Akvesoi-${{ needs.check.outputs.iosevkaVersion }}.zip">Unhinted</a></b>)</td></tr>
            <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;├&nbsp;<b>Akvesoi Term</b></td><td>Terminal</td><td>No</td><td><b><a href="https://github.com/g-hanwen/Akvesoi/releases/download/v${{ needs.check.outputs.iosevkaVersion }}/SuperTTC-SGr-AkvesoiTerm-${{ needs.check.outputs.iosevkaVersion }}.zip">Super TTC</a></b></td><td><b><a href="https://github.com/g-hanwen/Akvesoi/releases/download/v${{ needs.check.outputs.iosevkaVersion }}/PkgTTC-SGr-AkvesoiTerm-${{ needs.check.outputs.iosevkaVersion }}.zip">TTC</a></b></td><td><b><a href="https://github.com/g-hanwen/Akvesoi/releases/download/v${{ needs.check.outputs.iosevkaVersion }}/PkgTTF-AkvesoiTerm-${{ needs.check.outputs.iosevkaVersion }}.zip">TTF</a></b>&nbsp;(<b><a href="https://github.com/g-hanwen/Akvesoi/releases/download/v${{ needs.check.outputs.iosevkaVersion }}/PkgTTF-Unhinted-AkvesoiTerm-${{ needs.check.outputs.iosevkaVersion }}.zip">Unhinted</a></b>)</td><td><b><a href="https://github.com/g-hanwen/Akvesoi/releases/download/v${{ needs.check.outputs.iosevkaVersion }}/PkgWebFont-AkvesoiTerm-${{ needs.check.outputs.iosevkaVersion }}.zip">WebFont</a></b>&nbsp;(<b><a href="https://github.com/g-hanwen/Akvesoi/releases/download/v${{ needs.check.outputs.iosevkaVersion }}/PkgWebFont-Unhinted-AkvesoiTerm-${{ needs.check.outputs.iosevkaVersion }}.zip">Unhinted</a></b>)</td></tr>
            <tr><td>&nbsp;&nbsp;&nbsp;&nbsp;└&nbsp;<b>Akvesoi Mono</b></td><td>Fixed</td><td>No</td><td><b><a href="https://github.com/g-hanwen/Akvesoi/releases/download/v${{ needs.check.outputs.iosevkaVersion }}/SuperTTC-SGr-AkvesoiFixed-${{ needs.check.outputs.iosevkaVersion }}.zip">Super TTC</a></b></td><td><b><a href="https://github.com/g-hanwen/Akvesoi/releases/download/v${{ needs.check.outputs.iosevkaVersion }}/PkgTTC-SGr-AkvesoiFixed-${{ needs.check.outputs.iosevkaVersion }}.zip">TTC</a></b></td><td><b><a href="https://github.com/g-hanwen/Akvesoi/releases/download/v${{ needs.check.outputs.iosevkaVersion }}/PkgTTF-AkvesoiFixed-${{ needs.check.outputs.iosevkaVersion }}.zip">TTF</a></b>&nbsp;(<b><a href="https://github.com/g-hanwen/Akvesoi/releases/download/v${{ needs.check.outputs.iosevkaVersion }}/PkgTTF-Unhinted-AkvesoiFixed-${{ needs.check.outputs.iosevkaVersion }}.zip">Unhinted</a></b>)</td><td><b><a href="https://github.com/g-hanwen/Akvesoi/releases/download/v${{ needs.check.outputs.iosevkaVersion }}/PkgWebFont-AkvesoiFixed-${{ needs.check.outputs.iosevkaVersion }}.zip">WebFont</a></b>&nbsp;(<b><a href="https://github.com/g-hanwen/Akvesoi/releases/download/v${{ needs.check.outputs.iosevkaVersion }}/PkgWebFont-Unhinted-AkvesoiFixed-${{ needs.check.outputs.iosevkaVersion }}.zip">Unhinted</a></b>)</td></tr>
            </table>
          files: |
            src/release-archives/SuperTTC-Akvesoi-${{ needs.check.outputs.iosevkaVersion }}.zip
            src/release-archives/PkgTTC-Akvesoi-${{ needs.check.outputs.iosevkaVersion }}.zip
            src/release-archives/SuperTTC-SGr-Akvesoi-${{ needs.check.outputs.iosevkaVersion }}.zip
            src/release-archives/PkgTTC-SGr-Akvesoi-${{ needs.check.outputs.iosevkaVersion }}.zip
            src/release-archives/PkgTTF-Akvesoi-${{ needs.check.outputs.iosevkaVersion }}.zip
            src/release-archives/PkgTTF-Unhinted-Akvesoi-${{ needs.check.outputs.iosevkaVersion }}.zip
            src/release-archives/PkgWebFont-Akvesoi-${{ needs.check.outputs.iosevkaVersion }}.zip
            src/release-archives/PkgWebFont-Unhinted-Akvesoi-${{ needs.check.outputs.iosevkaVersion }}.zip
            src/release-archives/SuperTTC-SGr-AkvesoiTerm-${{ needs.check.outputs.iosevkaVersion }}.zip
            src/release-archives/PkgTTC-SGr-AkvesoiTerm-${{ needs.check.outputs.iosevkaVersion }}.zip
            src/release-archives/PkgTTF-AkvesoiTerm-${{ needs.check.outputs.iosevkaVersion }}.zip
            src/release-archives/PkgTTF-Unhinted-AkvesoiTerm-${{ needs.check.outputs.iosevkaVersion }}.zip
            src/release-archives/PkgWebFont-AkvesoiTerm-${{ needs.check.outputs.iosevkaVersion }}.zip
            src/release-archives/PkgWebFont-Unhinted-AkvesoiTerm-${{ needs.check.outputs.iosevkaVersion }}.zip
            src/release-archives/SuperTTC-SGr-AkvesoiMono-${{ needs.check.outputs.iosevkaVersion }}.zip
            src/release-archives/PkgTTC-SGr-AkvesoiMono-${{ needs.check.outputs.iosevkaVersion }}.zip
            src/release-archives/PkgTTF-AkvesoiMono-${{ needs.check.outputs.iosevkaVersion }}.zip
            src/release-archives/PkgTTF-Unhinted-AkvesoiMono-${{ needs.check.outputs.iosevkaVersion }}.zip
            src/release-archives/PkgWebFont-AkvesoiMono-${{ needs.check.outputs.iosevkaVersion }}.zip
            src/release-archives/PkgWebFont-Unhinted-AkvesoiMono-${{ needs.check.outputs.iosevkaVersion }}.zip

